### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by tnypxl** [gaslight/atom-cucumber-step#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [cucumber-step](https://github.com/gaslight/atom-cucumber-step) package, v0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /Users/tnypxl/.atom/packages/cucumber-step/lib/step-jumper.coffee:16

TypeError: Cannot read property '1' of null
  at StepJumper.module.exports.StepJumper.checkMatch (/Users/tnypxl/.atom/packages/cucumber-step/lib/step-jumper.coffee:16:59)
  at /Users/tnypxl/.atom/packages/cucumber-step/lib/cucumber-step.coffee:14:36
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:923:18
  at Task.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task.js:70:31)
  at ChildProcess.emit (events.js:119:17)
  at handleMessage (child_process.js:326:10)
  at Pipe.channel.onread (child_process.js:354:11)

```

### Commands

```
     -2:39.6 fuzzy-finder:toggle-file-finder (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -2:37.5 core:move-down (atom-text-editor.editor.mini)
     -2:37.2 core:confirm (atom-text-editor.editor.mini)
  2x -2:21.4 core:select-all (atom-text-editor.editor.is-focused)
     -2:11.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -2:07.3 core:confirm (atom-text-editor.editor.mini)
  2x -2:04.8 core:move-down (atom-text-editor.editor.is-focused)
  3x -2:02.4 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:00.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:59.1 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
     -0:55.1 settings-view:open (atom-text-editor.editor.is-focused)
     -0:42.7 core:select-all (atom-text-editor.editor.mini)
     -0:42.5 core:backspace (atom-text-editor.editor.mini)
     -0:37.5 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 cucumber-step:jump-to-step (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
cucumber, v0.4.1
cucumber-step, v0.1.2
language-gherkin, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dkarter** [comment]
I'm having the same issue

**Comment by wgottschalk-RMS** [comment]
I'm having the same error. The line for the error is `step-jumper.coffee:20`. My features file is nested a couple of files deep.
